add design concept
omega-bbs/docs pull request #1
Opened 2017-08-18 16:21 UTC by oott123

2017-08-18 16:40 UTC, lixiaoyan requested changes

2017-08-18 16:40 UTC, lixiaoyan commented on README.md
> +现在，并没有一款刚好“够用”的论坛系统。Discuz! 功能丰富但臃肿复杂，难以完成轻量级的交流，且架构老旧；Flarum 精致典雅但填坑无望，功能缺失严重而生态贫乏；Discourse 设计现代，但体量巨大且运行缓慢，不接底气。鉴于此，ω bbs 致力于构建一个适用于中文（甚至全球）社区的论坛社区。
`底气`?

2017-08-18 16:40 UTC, lixiaoyan commented on README.md
> +ω bbs 的绝大部分的特性只需要你进行安装即可使用，而无需经过复杂的配置。默认的部署方式加上一台[低至 2.5 美元/月](https://www.vultr.com/?ref=6959761)的 VPS 即可让你安心的撑过种子用户期。得益于 Docker 的广泛引用，你也可以通过 Kubernetes、Swarm 或 docker-compose 对其进行轻松进行横向扩展。
SSR 我不觉得能撑住...

2017-08-18 16:44 UTC, lixiaoyan approved these changes

2017-08-18 16:44 UTC, oott123 commented on README.md
> +ω bbs 的绝大部分的特性只需要你进行安装即可使用，而无需经过复杂的配置。默认的部署方式加上一台[低至 2.5 美元/月](https://www.vultr.com/?ref=6959761)的 VPS 即可让你安心的撑过种子用户期。得益于 Docker 的广泛引用，你也可以通过 Kubernetes、Swarm 或 docker-compose 对其进行轻松进行横向扩展。
vultr 2.5$ 的方案，整个跑起来应该没太多问题，前期用户少，可能一天 pv 都没 200 个，我觉得应该够用的

2017-08-19 02:54 UTC, oott123 commented
@oott123 @zh99998 起床 review 了

2017-08-19 03:35 UTC, zh99998 commented on README.md
添加一个正在开发中的说明吧，免得别人进来看到了以为是成品纠结....

2017-08-19 04:50 UTC, merged